version: '2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: cervejator
      POSTGRES_USER: cervejator
      POSTGRES_PASSWORD: fakeinitialpass
  redis:
    image: redis:3.2
  web:
    build: .
    environment:
      RAILS_ENV: "production"
      REDIS_URL: "redis://redis:6379"
      SECRET_KEY_BASE: "a0489e4ef023cb859fc7de7779ade0f493d5d8e20a249a4345e9605eadcf6578b0ceb78653a671b4fa65e509d967fa0944a983c6c59af9deb4c351dc782751c1"
      RAILS_SERVE_STATIC_FILES: "1" # remember to change this once we have a real web server and not rails s -- https://stackoverflow.com/questions/21969549/rails-application-css-asset-not-found-in-production-mode
    entrypoint: ["/bin/bash", "/web/lib/scripts/docker_run_pending_migrations.sh"]
    command: bundle exec rails s -b "0.0.0.0" -p 4000
    volumes:
      - /home/donato/cervejator:/web
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
      - mqtt
  subscriber:
    build:
      context: .
      dockerfile: Dockerfile.subscriber
    restart: always
    environment:
      RAILS_ENV: "production"
      REDIS_URL: "redis://redis:6379"
      SECRET_KEY_BASE: "a0489e4ef023cb859fc7de7779ade0f493d5d8e20a249a4345e9605eadcf6578b0ceb78653a671b4fa65e509d967fa0944a983c6c59af9deb4c351dc782751c1"
      MQTT_BROKER_HOST: "mqtt"
      MQTT_BROKER_PORT: "1883"
    command: bundle exec rake mqtt:subscriber
    volumes:
      - /home/donato/cervejator:/web
    depends_on:
      - redis
      - db
      - mqtt
  mqtt:
    image: 'donatoaz/mymosquitto'
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /home/donato/cervejator/mqtt/config:/mqtt/config:ro
      - /home/donato/cervejator/mqtt/data:/mqtt/data
      - /home/donato/cervejator/mqtt/log:/mqtt/log
  workers:
    build:
      context: .
      dockerfile: Dockerfile.subscriber
    environment:
      QUEUE: "*"
      RAILS_ENV: "production"
      REDIS_URL: "redis://redis:6379"
    command: bundle exec rake resque:work
    depends_on:
      - redis
      - db
  scheduler:
    build: .
    depends_on:
      - redis
      - workers
    command: bundle exec rake resque:scheduler
    environment:
      QUEUE: "*"
      RAILS_ENV: "production"
      REDIS_URL: "redis://redis:6379"
