redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

development:
  *redis

test:
  *redis

production:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: cervejator_production
